# --- Application ---
application.env=stg
application.version=@project.version@
application.upload.directory=/tmp/
application.port=8080
server.port=${PORT:8080}
# --- Mongodb ---
mongodb_connection.lottery=mongodb+srv://developer:Tq80kzTZLkQksnPZ@lottery.bfqbcot.mongodb.net/?retryWrites=true&w=majority&appName=lottery
