import { useState } from 'react';

export default function HomePage({ onNavigate }) {
  const [memberOpen, setMemberOpen] = useState(false);
  return <div className="reference-home">
    <header className="reference-header"><div className="reference-nav"><b className="reference-logo">3N <span>3nhay</span></b><nav><button onClick={() => onNavigate('result')}>Kết quả</button><button onClick={() => onNavigate('analysis')}>Thống kê</button><button onClick={() => setMemberOpen(true)}>Chiến lược 🔒</button></nav><button className="reference-login" onClick={() => setMemberOpen(true)}>Đăng nhập</button></div></header>
    <section className="reference-hero"><div><p>PHÂN TÍCH XSMB · DỮ LIỆU LỊCH SỬ</p><h1>Tra cứu và thống kê<br />xổ số miền Bắc</h1><p className="reference-lead">Dữ liệu kết quả, tần suất xuất hiện và công cụ phân tích được trình bày rõ ràng, dễ sử dụng.</p><button onClick={() => onNavigate('result')}>Xem kết quả</button><button className="reference-secondary" onClick={() => onNavigate('analysis')}>Xem thống kê</button></div></section>
    <section className="reference-stats"><article><b>Kết quả</b><h2>Tra cứu từng kỳ quay</h2><p>Xem đầy đủ các giải, bảng đầu – đuôi và lịch sử theo ngày.</p><button onClick={() => onNavigate('result')}>Tra cứu ngay →</button></article><article><b>Thống kê</b><h2>So sánh số liệu</h2><p>Nhập lô, chọn khoảng ngày và xem những ngày xuất hiện cùng nhau.</p><button onClick={() => onNavigate('analysis')}>Mở thống kê →</button></article><article className="reference-vip"><b>THÀNH VIÊN</b><h2>Chiến lược</h2><p>Công thức và kiểm thử lịch sử dành riêng cho tài khoản đã đăng nhập.</p><button onClick={() => setMemberOpen(true)}>Đăng nhập để xem →</button></article></section>
    <section className="reference-method"><p>THÔNG TIN THAM KHẢO</p><h2>Dữ liệu có thể kiểm tra lại</h2><div><article><b>01</b><h3>Nguồn dữ liệu</h3><p>Kết quả được lưu theo từng kỳ quay để phục vụ tra cứu.</p></article><article><b>02</b><h3>Thống kê</h3><p>Các chỉ số được tính từ khoảng thời gian người dùng chọn.</p></article><article><b>03</b><h3>Minh bạch</h3><p>Kết quả quá khứ không phải cam kết cho kết quả tương lai.</p></article></div></section>
    <section className="reference-faq"><h2>Câu hỏi thường gặp</h2><details><summary>Có thể tra cứu những dữ liệu nào?</summary><p>Kết quả XSMB theo ngày, đầu – đuôi, tần suất và dữ liệu so sánh lô.</p></details><details><summary>Chiến lược hoạt động thế nào?</summary><p>Khu vực này sử dụng các công thức và kiểm thử lịch sử; chỉ mở sau khi đăng nhập.</p></details></section>
    <footer>© {new Date().getFullYear()} 3nhay · kequaxsmb.online · Thông tin chỉ mang tính tham khảo.</footer>
    {memberOpen && <div className="member-modal"><div><button onClick={() => setMemberOpen(false)}>×</button><p>THÀNH VIÊN</p><h2>Đăng nhập để xem Chiến lược</h2><span>Hệ thống tài khoản sẽ được kết nối trước khi khu vực Chiến lược được công bố.</span></div></div>}
  </div>;
}
