package core.utils.common.enumeration;

public class TimeEnum {
    public static final int MILLISECOND_OF_FIVE_SECOND = 5 * 1000;
    public static final int MILLISECOND_OF_TEN_SECOND = 10 * 1000;
    public static final int MILLISECOND_OF_ONE_MINUTE = 60 * 1000;
    public static final int MILLISECOND_OF_FIVE_MINUTE = 5 * 60 * 1000;
    public static final int MILLISECOND_OF_30_MINUTE = 30 * 60 * 1000;
    public static final int MILLISECOND_OF_ONE_HOUR = 60 * 60 * 1000;
    public static final int MILLISECOND_OF_SIX_HOUR = 6 * 60 * 60 * 1000;
    public static final int MILLISECOND_OF_ONE_DAY = 24 * 60 * 60 * 1000;
    public static final int MILLISECOND_OF_SEVEN_DAY = 7 * 24 * 60 * 60 * 1000;
    public static final int SECOND_OF_ONE_MINUTE = 60;
    public static final int SECOND_OF_TWO_MINUTE = 2 * 60;
    public static final int SECOND_OF_FIVE_MINUTE = 5 * 60;
    public static final int SECOND_OF_THREE_MINUTE = 3 * 60;
    public static final int SECOND_OF_TEN_MINUTE = 10 * 60;
    public static final int SECOND_OF_90_MINUTE = 90 * 60;
    public static final int SECOND_OF_30_MINUTE = 30 * 60;
    public static final int SECOND_OF_ONE_HOUR = 60 * 60;
    public static final int SECOND_OF_TWO_HOUR = 2 * 60 * 60;
    public static final int SECOND_OF_SIX_HOUR = 6 * 60 * 60;
    public static final int SECOND_OF_ONE_DAY = 24 * 60 * 60;
    public static final int SECOND_OF_TWO_DAY = 2 * 24 * 60 * 60;
    public static final int SECOND_OF_THREE_DAY = 3 * 24 * 60 * 60;
    public static final int SECOND_OF_SEVEN_DAY = 7 * 24 * 60 * 60;
    public static final int SECOND_OF_ONE_MONTH = 30 * 24 * 60 * 60;
    public static final int SECOND_OF_21DAY = 21 * 24 * 60 * 60;
    public static final int SECOND_OF_SIX_MONTH = 6 * 30 * 24 * 60 * 60;

    public static final long LONG_MILLISECOND_OF_FIVE_SECOND = 5 * 1000L;
    public static final long LONG_MILLISECOND_OF_TEN_SECOND = 10 * 1000L;
    public static final long LONG_MILLISECOND_OF_ONE_SECOND = 1000L;
    public static final long LONG_MILLISECOND_OF_ONE_MINUTE = 60 * 1000L;
    public static final long LONG_MILLISECOND_OF_FIVE_MINUTE = 5 * 60 * 1000L;
    public static final long LONG_MILLISECOND_OF_TEN_MINUTE = 10 * 60 * 1000L;
    public static final long LONG_MILLISECOND_OF_30_MINUTE = 30 * 60 * 1000L;
    public static final long LONG_MILLISECOND_OF_ONE_HOUR = 60 * 60 * 1000L;
    public static final long LONG_MILLISECOND_OF_SIX_HOUR = 6 * 60 * 60 * 1000L;
    public static final long LONG_MILLISECOND_OF_ONE_DAY = 24 * 60 * 60 * 1000L;
    public static final long LONG_MILLISECOND_OF_SEVEN_DAY = 7 * 24 * 60 * 60 * 1000L;
    public static final long LONG_SECOND_OF_ONE_MINUTE = 60L;
    public static final long LONG_SECOND_OF_TWO_MINUTE = 2 * 60L;
    public static final long LONG_SECOND_OF_FIVE_MINUTE = 5 * 60L;
    public static final long LONG_SECOND_OF_TEN_MINUTE = 10 * 60L;
    public static final long LONG_SECOND_OF_90_MINUTE = 90 * 60L;
    public static final long LONG_SECOND_OF_30_MINUTE = 30 * 60L;
    public static final long LONG_SECOND_OF_ONE_HOUR = 60 * 60L;
    public static final long LONG_SECOND_OF_TWO_HOUR = 2 * 60 * 60L;
    public static final long LONG_SECOND_OF_SIX_HOUR = 6 * 60 * 60L;
    public static final long LONG_SECOND_OF_ONE_DAY = 24 * 60 * 60L;
    public static final long LONG_SECOND_OF_TWO_DAY = 2 * 24 * 60 * 60L;
    public static final long LONG_SECOND_OF_THREE_DAY = 3 * 24 * 60 * 60L;
    public static final long LONG_ECOND_OF_SEVEN_DAY = 7 * 24 * 60 * 60L;
    public static final long LONG_SECOND_OF_21_DAY = 21 * 24 * 60 * 60L;
    public static final long LONG_SECOND_OF_ONE_MONTH = 30 * 24 * 60 * 60L;
    public static final long LONG_SECOND_OF_SIX_MONTH = 6 * 30 * 24 * 60 * 60L;
}
